DROP TABLE IF EXISTS `CURRENCY_TYPE`;

CREATE TABLE CURRENCY_TYPE (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    VERSION BIGINT NOT NULL,
    CURRENCY_CODE VARCHAR(255) NOT NULL,
    CURRENCY_CH_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (CURRENCY_CODE)
);

COMMENT ON COLUMN CURRENCY_TYPE.ID IS 'id';
COMMENT ON COLUMN CURRENCY_TYPE.VERSION IS '版本';
COMMENT ON COLUMN CURRENCY_TYPE.CURRENCY_CODE IS '幣別(代碼)';
COMMENT ON COLUMN CURRENCY_TYPE.CURRENCY_CH_NAME IS '幣別(中文)';
